include("TypesTest.jl")
include("BasisTest.jl")
include("NuclearRepulsionTest.jl")
include("OverlapTest.jl")

run_typesparticles_test()
run_typesbasis_test()
#run_readbasis_test()
#run_retreadbasis_test()
run_nuclearrepulsion_test()
run_buildoverlap_test()
