#include("TypesTest.jl")
#include("BasisTest.jl")
#include("NuclearRepulsionTest.jl")
#include("OverlapTest.jl")
#include("KineticEnergyTest.jl")
#include("NuclearAttractionTest.jl")
include("ElecElecRepulsionTest.jl")

# run_typesparticles_test()
# run_typesbasis_test()
# run_readbasis_test()
# run_retreadbasis_test()
# run_nuclearrepulsion_test()
# run_buildoverlap_test()
# run_buildkineticenergy_test()
# run_buildnuclrattract_test()
run_buildelecelecrepul_test()
